import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "アプリサポート",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3362493734697220"
          crossOrigin="anonymous"></script>
        <link rel="icon" href="../public/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
