import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "エンジニアキャリア診断",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../public/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
